### PR TITLE
added loader to pokemon cards

### PR DESCRIPTION
**Pull request by Thanush19**

### CODE REVIEW

**Comment by TheShiveshNetwork** [comment]
Hey, @Thanush19 I really appreciate your work! Can you once check the deployment preview? It's not working, if you can fix that, I'll merge after seeing the preview.

**Comment by TheShiveshNetwork** [comment]
@Thanush19 resolve the confilcts.

**Comment by Thanush19** [comment]
@TheShiveshNetwork  conflicts has been resolved....

**Comment by TheShiveshNetwork** [comment]
The loader is constantly loading. It's not finishing to load in deployment. Is it the same with the development?
Screenshot
As of now I'm closing the issue as a fix has already been made.
If you are still interested to contribute, look over the other issues or you can open your own issue.
And if you fix the problem with this loader, add this too in the next PR.

Happy Hacktoberfest!

**Pull request closed without merging**
