### PR TITLE
Infinite Scroll is added.

### PR DESCRIPTION
**Pull request by darshitdudhaiya**

### CODE REVIEW

**Comment by TheShiveshNetwork** [comment]
@darshitdudhaiya can you do one modification? Instead of changing the offset, change the limit in the api fetch. I want the previously fetched pokemons to also be visible.

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork ok i would like to work on it.

**Comment by TheShiveshNetwork** [comment]
@darshitdudhaiya I've fixed the mentioned issue, but there is a sort of bug with your code I guess.  On re-render, it scrolls to top. I don't want that. Fix it!

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork  i got it.

**Comment by alexis-opolka** [comment]
Hi @darshitdudhaiya 👋🏼 and sorry for the jump in the discussion but do not hesitate to write

```txt
Fixes #<your-issue-number>
```

in your PR body for GitHub to automatically close the related issue when this PR will be merged ^-^.

N.B: See [GitHub Documentation - Linking a Pull Request to an Issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

**Comment by darshitdudhaiya** [comment]
@TheShiveshNetwork  i solved issue almost pls check out.

**Comment by TheShiveshNetwork** [comment]
It's not fully fixed, but I might merge until I get a better PR @darshitdudhaiya 
Btw, you can also checkout [React Scroll Component](https://www.npmjs.com/package/react-infinite-scroll-component)

**Comment by TheShiveshNetwork** [comment]
@darshitdudhaiya , if you make it better, you can contribute again, just mention me on #7

**Pull request merged**
