### PR TITLE
Updated Search Functionality

### LINKED ISSUE #9: Improve the pokemon search
## What does this issue mean?
Currently the search works on only the rendered pokemon cards. It should search in the whole pokemon response.

## Steps to fix the issue
- Use the pokeapi to get all the pokemons and filter for the searched keyword in pokemon name
- Display the filtered pokemon cards
- Optimize the code. It should not have multiple api calls that slow down the app.

## How to contribute
If you are interested, reply below and I'll assign this to you.
- Create a PR
- Submit and wait for response
- If the PR is reviewed, it wil be merged

### Happy Hacking !!!

### PR DESCRIPTION
**Pull request by Namatuzio**
Fixes #9 
* Added "Lazy Loading" to the home page in order to accommodate the now 1017 Pokemon. 
* Used the official PokeAPI URLs to grab Pokemon images. 
* Changed the images from the dream world artwork to the official art to accommodate post-gem 5 Pokemon

Hey @TheShiveshNetwork I updated the search functionality but I have one question, Sinistcha, DEX#1013 currently doesn't have any official artwork or sprites as these are typically taken from promotional material or the games themselves. This may be because the Pokemon is too new / niche in the DLC for material to have been released yet. 
image
image

I was wondering how you would want me to handle this unless it's fine that its card doesn't feature any artwork.

Thank you!

### CODE REVIEW

**Comment by TheShiveshNetwork** [comment]
Great work @Namatuzio It's perfect, as of what I wanted.
And yeah tell me if you can add a static image of "image not found" or some styled text for the pokemons for which sprites aren't available, that would be great.
Kudos!!

**Comment by Namatuzio** [comment]
Alright, @TheShiveshNetwork I updated the missing portrait to include the Pokeball loader image if the image of the Pokemon is missing.

image
I'm gonna mark this PR ready for review and of course, if you need anything changed just let me know.

**Comment by TheShiveshNetwork** [comment]
@Namatuzio there are some conflicts, can you resolve them for me to merge your PR?

**Comment by Namatuzio** [comment]
Hey @TheShiveshNetwork I'm currently attempting to fix the conflicts with this pr and it seems like Infinite Scroll does this: 
image
I was trying to work on a fix for this in my branch but I can't seem to properly replicate an infinitely scrolling page I believe it's because multiple API calls are made to keep re-fetching Pokemon and displaying them. 
As for multiples of the same Pokemon showing up, I was wondering if this is okay. As always, please let me know, thank you 😊

**Comment by TheShiveshNetwork** [comment]
If you can remove the infinite scroll, only lazy loading is also okay.

**Comment by Namatuzio** [comment]
@TheShiveshNetwork all done! If it's not too much trouble, would you be able to add the hacktoberfest-accepted label as well when you merge? Thanks again, I had a blast working on this functionality.

**Comment by TheShiveshNetwork** [comment]
All good, great work @Namatuzio 
Also I'd like to connect with you, we can build some better projects together may be.
If you have linkedin tell me.
Merging this one.
Welcome🍰!!!

**Pull request merged**
