### PR TITLE
Feature: Dark Mode Toggle and Styling

### LINKED ISSUE #12: add dark mode (my eyes hurt)

### PR DESCRIPTION
**Pull request by Namatuzio**
@TheShiveshNetwork 

Fixes #12 

- Added a dark mode toggle
- Adjusted theme for when dark mode is enabled
- Followed guidelines from the official [Tailwind CSS Dark Mode guide](https://tailwindcss.com/docs/dark-mode)

I'll post some screenshots of the UI updates but I want to know if you would like anything adjusted in terms of colours, placement, etc, for the implementation before any merge. 

Current toggle placement:
darkmode toggle button

Homepage colours:
Dark mode colours

Pokemon info styling:
info styling

I'll mark this as a draft for now and update it until it meets your standards!

### CODE REVIEW

**Comment by Namatuzio** [comment]
Ah, seems like there's some conflicts from unsynced commits, I'll patch that up real quick

**Comment by Namatuzio** [comment]
@TheShiveshNetwork Fixed up all the merge conflicts and added back all the dark mode changes, here's new screenshots reflecting the changes I forgot to sync:

Home Screen:
home screen

Home Screen (Dark Mode):
home screen dark mode

Pokemon Info:
pokemon info


Pokemon Info (Dark Mode):
info dark mode

**Comment by Namatuzio** [comment]
As always, if there are any changes you want, let me know and I'll add them, if not I'll open the PR for review!

**Comment by TheShiveshNetwork** [comment]
It looks good to me @Namatuzio 
Great work !!! :pizza:

**Comment by TheShiveshNetwork** [comment]
Also, if you're interested, checkout #24 
It is further enhancement to this.

**Pull request merged**
